name: CI
on:
    push:
        branches:
            - main
jobs:
    source-code-scan:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v4

            - name: 'SonarQube Scan'
              run: echo "Skip..."

    format-lint-lwc-tests:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v4

            - name: 'Install Volta'
              uses: volta-cli/action@v4

            - name: 'Restore node_modules cache'
              id: cache-npm
              uses: actions/cache@v4
              with:
                  path: node_modules
                  key: npm-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      npm-${{ env.cache-name }}-
                      npm-

            - name: 'Install npm dependencies'
              if: steps.cache-npm.outputs.cache-hit != 'true'
              run: HUSKY=0 npm ci

            - name: 'Code formatting verification with Prettier'
              run: npm run prettier:verify

            - name: 'Lint Lightning Web Components / Aura Components'
              run: npm run lint

            - name: 'Unit test Lightning Web Components'
              run: npm run test:unit:coverage

    scratch-org-test:
        runs-on: ubuntu-latest
        needs: format-lint-lwc-tests
        steps:
            - name: 'Install Salesforce CLI'
              run: |
                  npm install @salesforce/cli --location=global
                  nodeInstallPath=$(npm config get prefix)
                  echo "$nodeInstallPath/bin" >> $GITHUB_PATH
                  sf --version

            - name: 'Checkout source code'
              uses: actions/checkout@v4

            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
              shell: bash
              run: |
                  echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt
                  secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
                  if [ $secretFileSize == 1 ]; then
                      echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
                      exit 1;
                  fi

            - name: 'Authenticate Dev Hub'
              run: sf org login sfdx-url -f ./DEVHUB_SFDX_URL.txt -a devhub -d

            - name: 'Create scratch org'
              run: sf org create scratch -f config/project-scratch-def.json -a test-scratch-org -d -y 1

            - name: 'Push source to scratch org'
              run: sf project deploy start

            - name: 'Assign permissionset to default user'
              run: sf org assign permset -n dreamhouse

            - name: 'Import sample data'
              run: sf data tree import -p ./data/sample-data-plan.json

            - name: 'Run Apex tests'
              run: sf apex test run -c -r human -d ./tests/apex -w 20

            - name: 'Delete scratch org'
              if: always()
              run: sf org delete scratch -p -o test-scratch-org

    deploy-qa_uat_sit:
        runs-on: ubuntu-latest
        needs: scratch-org-test
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v4

            - name: 'Install Salesforce CLI'
              run: |
                  npm install @salesforce/cli --location=global
                  nodeInstallPath=$(npm config get prefix)
                  echo "$nodeInstallPath/bin" >> $GITHUB_PATH
                  sf --version

            - name: "Convert source"
              run: sf project convert source --root-dir ./force-app --output-dir ./release --package-name 'DreamHouse-${{github.run_id}}'

            - name: "List"
              run: ls ./release

            - name: "Deploy to QA/UAT/SIT"
              run: echo "No Sandbox to deploy... Skip..."

    runtime-test:
        runs-on: ubuntu-latest
        needs: deploy-qa_uat_sit
        steps:
            - name: "Robotframework Test"
              run: echo "Skip..."

            - name: "Postman(newman) Test"
              run: echo "Skip..."

    release-package-version:
        runs-on: ubuntu-latest
        needs: runtime-test
        steps:
            - name: 'Checkout source code'
              uses: actions/checkout@v4

            - name: 'Install Salesforce CLI'
              run: |
                  npm install @salesforce/cli --location=global
                  nodeInstallPath=$(npm config get prefix)
                  echo "$nodeInstallPath/bin" >> $GITHUB_PATH
                  sf --version

            - name: 'Populate auth file with DEVHUB_SFDX_URL secret'
              shell: bash
              run: |
                  echo ${{ secrets.DEVHUB_SFDX_URL }} > ./DEVHUB_SFDX_URL.txt
                  secretFileSize=$(wc -c "./DEVHUB_SFDX_URL.txt" | awk '{print $1}')
                  if [ $secretFileSize == 1 ]; then
                      echo "Missing DEVHUB_SFDX_URL secret. Is this workflow running on a fork?";
                      exit 1;
                  fi

            - name: 'Authenticate Dev Hub'
              run: sf org login sfdx-url -f ./DEVHUB_SFDX_URL.txt -a devhub -d

            - name: 'Create package version'
              id: createPackageVersion
              run: |
                  set +e
                  json=$(sf package version create -p Dreamhouse -x -w 20 -f config/project-scratch-def.json --json)
                  echo $json
                  status=$(echo $json | jq '.status')
                  if [ $status == "0" ]; then
                      packageVersionId=$(echo $json | jq -r '.result.SubscriberPackageVersionId')
                      echo "packageVersionId=$packageVersionId" >> $GITHUB_OUTPUT
                  else
                      echo "Failed to create package version"
                  fi
                  exit $status

            - name: 'Wait for package replication'
              run: sleep 360s

            - name: 'Create scratch org'
              run: sf org create scratch -f config/project-scratch-def.json -a uat-scratch-org -d -y 1

            - name: 'Install new package version in scratch org'
              run: sf package install -p ${{ steps.createPackageVersion.outputs.packageVersionId }} -w 10 -o uat-scratch-org -r

            - name: 'Update package install link in readme'
              run: |
                  packageVersionId="${{ steps.createPackageVersion.outputs.packageVersionId }}"
                  packageLinkRegex="https:\/\/login\.salesforce\.com\/packaging\/installPackage\.apexp\?p0=[a-zA-ZA-ZA-Z0-9]{18}"
                  newPackageLink="https://login.salesforce.com/packaging/installPackage.apexp?p0=${packageVersionId}"
                  echo $newPackageLink